allowBuilds:
  '@parcel/watcher': false
  '@prisma/client': false
  '@prisma/engines': false
  '@scarf/scarf': false
  '@tree-sitter-grammars/tree-sitter-yaml': false
  bcrypt: true
  core-js-pure: false
  env-nextjs: true
  esbuild: false
  prisma: false
  tree-sitter: false
  tree-sitter-json: false
  unrs-resolver: false
